<header>
  <nav id="navbar" class="nav">
    <a id="nav-logo" href="index.php"
      ><img src="images/atom.svg " width="50" height="50" alt="Logo" /></a
    ><br />
    <ul class="nav-list">
      <li>
        <a href="index.php">Home</a>
      </li>
      <li>
        <div class="apply-head">
          <button class="apply-tag">Careers</button>
          <ul class="dropdown-content">
            <li><a href="jobs.php">Vacancies</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="manage.php?view=All&orderby=EOInumber&submit=View">Manage</a></li>
          </ul>
        </div>
      </li>
      <li>
        <a href="about.php">About</a>
      </li>
      <li>
        <div class="apply-head">
          <button class="apply-tag">Enhancements</button>
          <ul class="dropdown-content">
            <li><a href="enhancements.php">HTML + CSS</a></li>
            <li><a href="enhancements2.php">JavaScript</a></li>
            <li><a href="phpenhancements.php">PHP</a></li>
          </ul>
        </div>
      </li>
    </ul>
    <div class="burger">
      <div class="line1"></div>
      <div class="line2"></div>
      <div class="line3"></div>
    </div>
    <div class="login">
      <a id="logout" href="login.php">
      <!-- All the icons are taken from https://www.flaticon.com/-->
      <img src="images/login.svg" title="Login" width="35" height="35" alt="Login" /></a>
    </div>
    <div class="dark-switch active">
      <!-- All the icons are taken from https://www.flaticon.com/-->
      <img src="images/dark-switch.svg" title="Dark Mode" alt="Dark Mode" />
    </div>

    <div class="light-switch">
      <!-- All the icons are taken from https://www.flaticon.com/-->
      <img src="images/light-switch.svg" title="Light Mode" alt="Light Mode" />
    </div>
  </nav>
</header>
